<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="TCatSysManagerLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>3</VersionMinor>
      <VersionMajor>3</VersionMajor>
      <Guid>3c49d6c3-93dc-11d0-b162-00a0248c244b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="7.0.172" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="envdte" Version="17.14.40260" />
    <PackageReference Include="envdte80" Version="17.14.40260" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
  </ItemGroup>

</Project>
